### PR TITLE
Add search-as-you-type example 

### PR DESCRIPTION
**Pull request by yakhinvadim**
This PR adds a new example page to sandbox and docs.

New sandbox page:

https://user-images.githubusercontent.com/11838280/167008950-5561d532-a495-45bb-ac57-8a9ea474db8c.mp4

New docs page (the embed is not working yet since the code is still in PR):
image

I put the new section below the tutorials since users need to go through a tutorial first and then follow the examples.

### CODE REVIEW

**Comment by elasticdocs** [comment]
:rocket: Built _docs-elastic-co_ successfully!

* https://docs-elastic-2zs2iooww-elastic-dev.vercel.app

* Built with commit de13c27b68977de46ab0819b30189dbeeb15c4f5

> Issues? Visit #next-docs in Slack

**Review by JasonStoltz — APPROVED** [review]

**Comment by yakhinvadim** [comment]
@goodroot 



The bot posted a message with success, but CI is failing. Ok to merge?

**Comment by goodroot** [comment]
@yakhinvadim Ah! In the midst of some refactoring. Yes, good to go.

Thanks for patience, pipeline almost settled. :)

**Comment by elasticdocs** [comment]
:bug: _Build docs-elastic-co failed!_

* Built commit 583349e742631ad453cb13cf057056c5307db139

* Check below to see the log and troubleshoot.

> Stuck? Visit #next-docs in Slack.

---
<details>
  <summary>Click to see error log for 583349e742631ad453cb13cf057056c5307db139 >> </summary>
    ```bash

    
    
    ```
</details>

**Pull request merged**
