### PR TITLE
Editing: Initial pass on tutorials, ES connector

### PR DESCRIPTION
**Pull request by zumwalt**
## Description
This PR includes edits (some heavy-handed, apologies!) to both tutorial documents and the ES connector doc, along with updated images for the App Search tutorial. 

### General
- Renames the tutorials to be product-oriented — App Search and Elasticsearch, respectively. Should also assist with SEO value.

### ES connector
- Added a clear callout about security concerns
- elasticsearch → Elasticsearch, kibana → Kibana where appropriate

### ES tutorial
- Adds a clear callout for security concerns
- minor copy edits

### App Search tutorial
_This one is heavy handed (sorry!)_
- Removes the engine creation → ingestion flow in favor of utilizing the sample engine
- Updates the images to be of a similar size and shadowless (Docsmobile takes care of shadows)
- Minor copy additions
- Minor copy edits

### CODE REVIEW

**Review by joemcelroy — DISMISSED** [review]

**Comment by joemcelroy** [comment]
love the changes. Thanks so much :)

**Comment by joemcelroy** [comment]
Got a build fail on vercel, does it run locally?

**Comment by goodroot** [comment]
Hey folks :) -- useful/accessible logs are on the roadmap.

```
Error occurred prerendering page "/quick-start". Read more: https://nextjs.org/docs/messages/prerender-error
--
07:11:15.701 | Error: Broken link! Invalid link to page id `advanced` in `DocLink`
07:11:15.702 | at UndefinedIdError (/vercel/path0/search-ui/docs/.docsmobile/.next/server/pages/[...slug].js:22803:11)
07:11:15.702 | at d (/vercel/path0/search-ui/docs/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
07:11:15.702 | at $a (/vercel/path0/search-ui/docs/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
07:11:15.702 | at a.b.render (/vercel/path0/search-ui/docs/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
07:11:15.703 | at a.b.read (/vercel/path0/search-ui/docs/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
07:11:15.703 | at renderToString (/vercel/path0/search-ui/docs/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
07:11:15.703 | at /vercel/path0/search-ui/docs/.docsmobile/.next/server/pages/[...slug].js:28314:58
07:11:15.704 | at async getStaticProps (/vercel/path0/search-ui/docs/.docsmobile/.next/server/pages/[...slug].js:28484:7)
07:11:15.704 | at async renderToHTML (/vercel/path0/search-ui/docs/node_modules/next/dist/next-server/server/render.js:27:1780)
07:11:15.704 | at async /vercel/path0/search-ui/docs/node_modules/next/dist/export/worker.js:26:6
```

I'll take a look -- as it says, a broken link somewhere.

**Comment by goodroot** [comment]
As shared on [Slack](https://elastic.slack.com/archives/C02SV94FAQL/p1649948002465139):

[https://github.com/elastic/search-ui/commit/e98c6babb962bafda282d149f601586f6dd940b9#diff-9b01a299afe87b200045072d7[…]0cf5b11ca7aa5a8176108fd7376a60](https://github.com/elastic/search-ui/commit/e98c6babb962bafda282d149f601586f6dd940b9#diff-9b01a299afe87b200045072d72205328420cf5b11ca7aa5a8176108fd7376a60)
The page with id advanced was removed with the above commit & so the failure is because there are likely still existing links to the page. You’ll have to update them in all files.

For example:

```
It exposes the <DocLink id="advanced" section="state" text="State" /> and <DocLink id="advanced" section="actions" text="Actions" /> of the core in a <DocLink id="advanced" section="context" text="Context" />.
```

These would need to point to a new `id`. :)

**Comment by zumwalt** [comment]
Thanks Kellen! It's interesting that the build is still failing now that the `/quick-start` file has been removed.

**Comment by elasticdocs** [comment]
:rocket: Built _search-ui_ successfully!

* [View deploy preview](https://search-18uegyzep-elastic-dev.vercel.app)

* Built with commit f2699f3a4daffef8b211c95ca5b951a23db60131

> Issues? Visit #next-docs in Slack

**Pull request merged**
