### PR TITLE
Correct exports for nuxt/svelte

### LINKED ISSUE #952: SvelteKit + Typescript module import issue
**Describe the bug**
When using search-ui with SvelteKit the module import is not working.

**To Reproduce**
` import { SearchDriver } from "@elastic/search-ui";`

Returns this error
```
import { SearchDriver } from "@elastic/search-ui";
         ^^^^^^^^^^^^
SyntaxError: Named export 'SearchDriver' not found. The requested module '@elastic/search-ui' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@elastic/search-ui';
const { SearchDriver } = pkg;
```

**Which backends and packages are you using:**
```
{
 ...
 "@elastic/search-ui": "^1.19.1",
 "svelte": "^3.54.0",
 "typescript": "^4.9.3",
 "vite": "^4.0.0",
}
```

### PR DESCRIPTION
**Pull request by ehibes**
## Description
On Nuxt3 or Svelte projects, an 500 error is returned with this message :

> SyntaxError: Named export 'SearchDriver' not found. The requested module '@elastic/search-ui' is a CommonJS module, which may not support all module.exports as named exports.

## List of changes
Add correct exports on package.json files to use ESM module on SvelteKit or Nuxt
```
"exports": {
    ".": {
      "import": "./lib/esm/index.js",
      "require": "./lib/cjs/index.js"
    }
  }
}
```

## Associated Github Issues
Resolve #952 #938 #953

### CODE REVIEW

**Comment by ehibes** [comment]
I signed the Contributor Agreement, how to recheck it ?

**Comment by Finnepinnen** [comment]
It looks like this was not merged into the elastic:main @joemcelroy

**Comment by ehibes** [comment]
Yes, I confirm that it was not merged. Can you reopen this pull request ?

**Comment by Finnepinnen** [comment]
Is there anything I can do to bump this pull request?

**Comment by Finnepinnen** [comment]
I'm so excited to get this reviewed!

**Comment by miguelgrinberg** [comment]
Moved to #1043

**Pull request closed without merging**
