### PR TITLE
Fix boolean facet check status

### PR DESCRIPTION
**Pull request by jasontk19**
#482  Description
Make sure that checkbox shows checked/unchecked depending on value of `isSelected` in case filter value is set via function call rather than via clicking the checkbox.

## Associated Github Issues
#490

### CODE REVIEW

**Comment by JasonStoltz** [comment]
I'll review this today, please sign the CLA.

**Comment by JasonStoltz** [comment]
CI is botched right now, don't worry about the failure.

**Comment by JasonStoltz** [comment]
This is great and I'd love to merge this in and publish it, I just need 2 things:

1. I need you to sign the CLA. Are you able to do this?

2. The snapshot test for BooleanFacet is broken. Please run the following command to fix it, and commit the result.

```
cd packages/react-search-ui-views
npx jest -u
```

Thanks!

**Comment by jasontk19** [comment]
@JasonStoltz I signed the CLA but not sure what next steps are to get this to be recognized by the CLA checker?

I will take a look at the test.

**Comment by JasonStoltz** [comment]
Cool, it's super easy to do. I'll submit a PR to your branch, if you just merge it we should be good.

**Comment by JasonStoltz** [comment]
Thanks so much for this contribution. It is now available in 1.4.0-rc.3

**Pull request merged**
