### PR TITLE
Fix debounce sync to url issue

### PR DESCRIPTION
**Pull request by gerardosabetta**
## Description
This PR kills any outstanding debounced `pushStateToURL` requests.

## List of changes
1. Calls `cancelByName` on teardown
2. Adds test to cover the above change

## Associated Github Issues
https://github.com/elastic/search-ui/issues/902

### CODE REVIEW

**Comment by joemcelroy** [comment]
thanks for your contribution @gerardosabetta! Will review today and get a release.

**Comment by gerardosabetta** [comment]
Thanks a lot @joemcelroy

**Review by joemcelroy — APPROVED** [review]

**Comment by joemcelroy** [comment]
@gerardosabetta theres an issue with the build ATM so might take longer for the release. Im back on monday so will take a look at that asap.

**Comment by gerardosabetta** [comment]
No rush at all, thanks for the approve! @joemcelroy

**Comment by joemcelroy** [comment]
now released under @elastic/search-ui@1.18.3

**Pull request merged**
