### PR TITLE
Efficent generation of filters for App Search Connector 

### PR DESCRIPTION
**Pull request by joemcelroy**
fixes https://github.com/elastic/search-ui/issues/837. 

- We are currently creating a new "filter" per value, even if it was grouped together inside values. This hits a ceiling fast with only 32 filters can be applied. 
- we should be using one filter per field with an **array** of values. https://www.elastic.co/guide/en/app-search/current/filters.html#filters-arrays-all-none
- ranges will not be able to be grouped together. Requires a filter per range type

### CODE REVIEW

**Comment by joemcelroy** [comment]
@JasonStoltz This one you might know more about its history. Im still unsure why the rollup function split grouped filter values into individual filters. This PR should now increase the limit from 32 filter values o 1024 filter values and works on our sandbox environment.

**Comment by JasonStoltz** [comment]
I think the reasoning is that these two are not necessarily functionally equivalent.


initial must match "additional values" AND "and values" AND "and even more values"
```
        all: [
          { initial: "additional values" },
          { initial: "and values" },
          { initial: "and even more values" }
        ]
```

initial must match "additional values" OR "and values" OR "and even more values"
```
        all: [
          {
            initial: ["additional values", "and values", "and even more values"]
          }
        ]
```

I think that as soon as you use the array syntax, the values implicitly become "OR"d. Let me do some quick testing to verify this.

**Comment by JasonStoltz** [comment]
```
{
  "query": "",
  "filters": {
      "all": [{
          "states": ["Alaska", "California"]
      }]
  }
}
```

Is functionally equivalent to:
```
{
  "query": "",
  "filters": {
      "all": [{
          "any": [{
            "states": ["Alaska"]
          },{
            "states": ["California"]
          }]
      }]
  }
}
```

**Comment by joemcelroy** [comment]
thanks @JasonStoltz that makes sense. I will update the PR to see if the filter is an "any" type and preserve the array of values, else create as before a filter for each value.

**Review by JasonStoltz — APPROVED** [review]

**Pull request merged**
